server:
  port: 8081
  servlet:
    context-path: /olx
  forward-headers-strategy: framework
spring:
  application:
    name: olx-login
  datasource:
    url: jdbc:mysql://localhost:3306/olxlogin
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: sushg12
  expiration.ms: 3600000
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /v3/api-docs
      
      
